feat: add Hero component
pulsate-dev/website pull request #22
Opened 2024-08-15 11:41 UTC by Allianaab2m

close #11

2024-08-15 12:08 UTC, laminne reviewed
Join Nowのボタンになんの機能を持たせるかについて考える必要がありそう

2024-08-15 12:08 UTC, laminne commented on app/components/Hero.tsx
> +        </Button>
こちらには必要なさそう(Disableされるわけじゃないので)

2024-08-15 14:27 UTC, m1sk9 commented
> Join Nowのボタンになんの機能を持たせるかについて考える必要がありそう
@laminne 

え, 普通にドキュメントの Getting Started へのリンクじゃないんですか？

2024-08-15 14:32 UTC, laminne commented
> え, 普通にドキュメントの Getting Started へのリンクじゃないんですか？

それなら"Getting started"とか、"Learn more"とすべきな気がします

2024-08-15 14:43 UTC, m1sk9 requested changes

2024-08-15 14:43 UTC, m1sk9 commented on i18n/locales/en_US.json
> +    "joinButton": "Join now",
`Getting Started` ( `gettingStartedButton` ? ) に翻訳を変えましょう

2024-08-15 14:43 UTC, m1sk9 commented on i18n/locales/ja_JP.json
> +    "joinButton": "今すぐ参加",
`はじめる` に翻訳を変えましょう

2024-08-19 06:44 UTC, m1sk9 approved these changes

2024-08-19 06:44 UTC, merged